version: '3.8'

services:
  piper-simple-api:
    build:
      context: https://github.com/Anusio/PIPER-SIMPLE-API.git
      dockerfile: Dockerfile
    ports:
      - "5501:5501"
    volumes:
      - ./piper_speakers/:/usr/src/piper_speakers/
    environment:
      - PIPER_GPU=false
