from enum import Enum


class PiperVoicesToDownload(Enum):
    ARABIC__AR_JO__KAREEM__LOW = 'ARABIC__AR_JO__KAREEM__LOW'
    ARABIC__AR_JO__KAREEM__MEDIUM = 'ARABIC__AR_JO__KAREEM__MEDIUM'
    CATALAN__CA_ES__UPC_ONA__X_LOW = 'CATALAN__CA_ES__UPC_ONA__X_LOW'
    CATALAN__CA_ES__UPC_ONA__MEDIUM = 'CATALAN__CA_ES__UPC_ONA__MEDIUM'
    CATALAN__CA_ES__UPC_PAU__X_LOW = 'CATALAN__CA_ES__UPC_PAU__X_LOW'
    CZECH__CS_CZ__JIRKA__LOW = 'CZECH__CS_CZ__JIRKA__LOW'
    CZECH__CS_CZ__JIRKA__MEDIUM = 'CZECH__CS_CZ__JIRKA__MEDIUM'
    WELSH__CY_GB__GWRYW_GOGLEDDOL__MEDIUM = 'WELSH__CY_GB__GWRYW_GOGLEDDOL__MEDIUM'
    DANISH__DA_DK__TALESYNTESE__MEDIUM = 'DANISH__DA_DK__TALESYNTESE__MEDIUM'
    GERMAN__DE_DE__EVA_K__X_LOW = 'GERMAN__DE_DE__EVA_K__X_LOW'
    GERMAN__DE_DE__KARLSSON__LOW = 'GERMAN__DE_DE__KARLSSON__LOW'
    GERMAN__DE_DE__KERSTIN__LOW = 'GERMAN__DE_DE__KERSTIN__LOW'
    GERMAN__DE_DE__MLS__MEDIUM = 'GERMAN__DE_DE__MLS__MEDIUM'
    GERMAN__DE_DE__PAVOQUE__LOW = 'GERMAN__DE_DE__PAVOQUE__LOW'
    GERMAN__DE_DE__RAMONA__LOW = 'GERMAN__DE_DE__RAMONA__LOW'
    GERMAN__DE_DE__THORSTEN__LOW = 'GERMAN__DE_DE__THORSTEN__LOW'
    GERMAN__DE_DE__THORSTEN__MEDIUM = 'GERMAN__DE_DE__THORSTEN__MEDIUM'
    GERMAN__DE_DE__THORSTEN__HIGH = 'GERMAN__DE_DE__THORSTEN__HIGH'
    GERMAN__DE_DE__THORSTEN_EMOTIONAL__MEDIUM = 'GERMAN__DE_DE__THORSTEN_EMOTIONAL__MEDIUM'
    GREEK__EL_GR__RAPUNZELINA__LOW = 'GREEK__EL_GR__RAPUNZELINA__LOW'
    ENGLISH__EN_GB__ALAN__LOW = 'ENGLISH__EN_GB__ALAN__LOW'
    ENGLISH__EN_GB__ALAN__MEDIUM = 'ENGLISH__EN_GB__ALAN__MEDIUM'
    ENGLISH__EN_GB__ALBA__MEDIUM = 'ENGLISH__EN_GB__ALBA__MEDIUM'
    ENGLISH__EN_GB__ARU__MEDIUM = 'ENGLISH__EN_GB__ARU__MEDIUM'
    ENGLISH__EN_GB__CORI__MEDIUM = 'ENGLISH__EN_GB__CORI__MEDIUM'
    ENGLISH__EN_GB__CORI__HIGH = 'ENGLISH__EN_GB__CORI__HIGH'
    ENGLISH__EN_GB__JENNY_DIOCO__MEDIUM = 'ENGLISH__EN_GB__JENNY_DIOCO__MEDIUM'
    ENGLISH__EN_GB__NORTHERN_ENGLISH_MALE__MEDIUM = 'ENGLISH__EN_GB__NORTHERN_ENGLISH_MALE__MEDIUM'
    ENGLISH__EN_GB__SEMAINE__MEDIUM = 'ENGLISH__EN_GB__SEMAINE__MEDIUM'
    ENGLISH__EN_GB__SOUTHERN_ENGLISH_FEMALE__LOW = 'ENGLISH__EN_GB__SOUTHERN_ENGLISH_FEMALE__LOW'
    ENGLISH__EN_GB__VCTK__MEDIUM = 'ENGLISH__EN_GB__VCTK__MEDIUM'
    ENGLISH__EN_US__AMY__LOW = 'ENGLISH__EN_US__AMY__LOW'
    ENGLISH__EN_US__AMY__MEDIUM = 'ENGLISH__EN_US__AMY__MEDIUM'
    ENGLISH__EN_US__ARCTIC__MEDIUM = 'ENGLISH__EN_US__ARCTIC__MEDIUM'
    ENGLISH__EN_US__BRYCE__MEDIUM = 'ENGLISH__EN_US__BRYCE__MEDIUM'
    ENGLISH__EN_US__DANNY__LOW = 'ENGLISH__EN_US__DANNY__LOW'
    ENGLISH__EN_US__HFC_FEMALE__MEDIUM = 'ENGLISH__EN_US__HFC_FEMALE__MEDIUM'
    ENGLISH__EN_US__HFC_MALE__MEDIUM = 'ENGLISH__EN_US__HFC_MALE__MEDIUM'
    ENGLISH__EN_US__JOE__MEDIUM = 'ENGLISH__EN_US__JOE__MEDIUM'
    ENGLISH__EN_US__JOHN__MEDIUM = 'ENGLISH__EN_US__JOHN__MEDIUM'
    ENGLISH__EN_US__KATHLEEN__LOW = 'ENGLISH__EN_US__KATHLEEN__LOW'
    ENGLISH__EN_US__KRISTIN__MEDIUM = 'ENGLISH__EN_US__KRISTIN__MEDIUM'
    ENGLISH__EN_US__KUSAL__MEDIUM = 'ENGLISH__EN_US__KUSAL__MEDIUM'
    ENGLISH__EN_US__L2ARCTIC__MEDIUM = 'ENGLISH__EN_US__L2ARCTIC__MEDIUM'
    ENGLISH__EN_US__LESSAC__LOW = 'ENGLISH__EN_US__LESSAC__LOW'
    ENGLISH__EN_US__LESSAC__MEDIUM = 'ENGLISH__EN_US__LESSAC__MEDIUM'
    ENGLISH__EN_US__LESSAC__HIGH = 'ENGLISH__EN_US__LESSAC__HIGH'
    ENGLISH__EN_US__LIBRITTS__HIGH = 'ENGLISH__EN_US__LIBRITTS__HIGH'
    ENGLISH__EN_US__LIBRITTS_R__MEDIUM = 'ENGLISH__EN_US__LIBRITTS_R__MEDIUM'
    ENGLISH__EN_US__LJSPEECH__MEDIUM = 'ENGLISH__EN_US__LJSPEECH__MEDIUM'
    ENGLISH__EN_US__LJSPEECH__HIGH = 'ENGLISH__EN_US__LJSPEECH__HIGH'
    ENGLISH__EN_US__NORMAN__MEDIUM = 'ENGLISH__EN_US__NORMAN__MEDIUM'
    ENGLISH__EN_US__RYAN__LOW = 'ENGLISH__EN_US__RYAN__LOW'
    ENGLISH__EN_US__RYAN__MEDIUM = 'ENGLISH__EN_US__RYAN__MEDIUM'
    ENGLISH__EN_US__RYAN__HIGH = 'ENGLISH__EN_US__RYAN__HIGH'
    SPANISH__ES_ES__CARLFM__X_LOW = 'SPANISH__ES_ES__CARLFM__X_LOW'
    SPANISH__ES_ES__DAVEFX__MEDIUM = 'SPANISH__ES_ES__DAVEFX__MEDIUM'
    SPANISH__ES_ES__MLS_10246__LOW = 'SPANISH__ES_ES__MLS_10246__LOW'
    SPANISH__ES_ES__MLS_9972__LOW = 'SPANISH__ES_ES__MLS_9972__LOW'
    SPANISH__ES_ES__SHARVARD__MEDIUM = 'SPANISH__ES_ES__SHARVARD__MEDIUM'
    SPANISH__ES_MX__ALD__MEDIUM = 'SPANISH__ES_MX__ALD__MEDIUM'
    SPANISH__ES_MX__CLAUDE__HIGH = 'SPANISH__ES_MX__CLAUDE__HIGH'
    FARSI__FA_IR__AMIR__MEDIUM = 'FARSI__FA_IR__AMIR__MEDIUM'
    FARSI__FA_IR__GYRO__MEDIUM = 'FARSI__FA_IR__GYRO__MEDIUM'
    FINNISH__FI_FI__HARRI__LOW = 'FINNISH__FI_FI__HARRI__LOW'
    FINNISH__FI_FI__HARRI__MEDIUM = 'FINNISH__FI_FI__HARRI__MEDIUM'
    FRENCH__FR_FR__GILLES__LOW = 'FRENCH__FR_FR__GILLES__LOW'
    FRENCH__FR_FR__MLS__MEDIUM = 'FRENCH__FR_FR__MLS__MEDIUM'
    FRENCH__FR_FR__MLS_1840__LOW = 'FRENCH__FR_FR__MLS_1840__LOW'
    FRENCH__FR_FR__SIWIS__LOW = 'FRENCH__FR_FR__SIWIS__LOW'
    FRENCH__FR_FR__SIWIS__MEDIUM = 'FRENCH__FR_FR__SIWIS__MEDIUM'
    FRENCH__FR_FR__TOM__MEDIUM = 'FRENCH__FR_FR__TOM__MEDIUM'
    FRENCH__FR_FR__UPMC__MEDIUM = 'FRENCH__FR_FR__UPMC__MEDIUM'
    HUNGARIAN__HU_HU__ANNA__MEDIUM = 'HUNGARIAN__HU_HU__ANNA__MEDIUM'
    HUNGARIAN__HU_HU__BERTA__MEDIUM = 'HUNGARIAN__HU_HU__BERTA__MEDIUM'
    HUNGARIAN__HU_HU__IMRE__MEDIUM = 'HUNGARIAN__HU_HU__IMRE__MEDIUM'
    ICELANDIC__IS_IS__BUI__MEDIUM = 'ICELANDIC__IS_IS__BUI__MEDIUM'
    ICELANDIC__IS_IS__SALKA__MEDIUM = 'ICELANDIC__IS_IS__SALKA__MEDIUM'
    ICELANDIC__IS_IS__STEINN__MEDIUM = 'ICELANDIC__IS_IS__STEINN__MEDIUM'
    ICELANDIC__IS_IS__UGLA__MEDIUM = 'ICELANDIC__IS_IS__UGLA__MEDIUM'
    ITALIAN__IT_IT__PAOLA__MEDIUM = 'ITALIAN__IT_IT__PAOLA__MEDIUM'
    ITALIAN__IT_IT__RICCARDO__X_LOW = 'ITALIAN__IT_IT__RICCARDO__X_LOW'
    GEORGIAN__KA_GE__NATIA__MEDIUM = 'GEORGIAN__KA_GE__NATIA__MEDIUM'
    KAZAKH__KK_KZ__ISEKE__X_LOW = 'KAZAKH__KK_KZ__ISEKE__X_LOW'
    KAZAKH__KK_KZ__ISSAI__HIGH = 'KAZAKH__KK_KZ__ISSAI__HIGH'
    KAZAKH__KK_KZ__RAYA__X_LOW = 'KAZAKH__KK_KZ__RAYA__X_LOW'
    LUXEMBOURGISH__LB_LU__MARYLUX__MEDIUM = 'LUXEMBOURGISH__LB_LU__MARYLUX__MEDIUM'
    NEPALI__NE_NP__GOOGLE__X_LOW = 'NEPALI__NE_NP__GOOGLE__X_LOW'
    NEPALI__NE_NP__GOOGLE__MEDIUM = 'NEPALI__NE_NP__GOOGLE__MEDIUM'
    DUTCH__NL_BE__NATHALIE__X_LOW = 'DUTCH__NL_BE__NATHALIE__X_LOW'
    DUTCH__NL_BE__NATHALIE__MEDIUM = 'DUTCH__NL_BE__NATHALIE__MEDIUM'
    DUTCH__NL_BE__RDH__X_LOW = 'DUTCH__NL_BE__RDH__X_LOW'
    DUTCH__NL_BE__RDH__MEDIUM = 'DUTCH__NL_BE__RDH__MEDIUM'
    DUTCH__NL_NL__MLS__MEDIUM = 'DUTCH__NL_NL__MLS__MEDIUM'
    DUTCH__NL_NL__MLS_5809__LOW = 'DUTCH__NL_NL__MLS_5809__LOW'
    DUTCH__NL_NL__MLS_7432__LOW = 'DUTCH__NL_NL__MLS_7432__LOW'
    NORWEGIAN__NO_NO__TALESYNTESE__MEDIUM = 'NORWEGIAN__NO_NO__TALESYNTESE__MEDIUM'
    POLISH__PL_PL__DARKMAN__MEDIUM = 'POLISH__PL_PL__DARKMAN__MEDIUM'
    POLISH__PL_PL__GOSIA__MEDIUM = 'POLISH__PL_PL__GOSIA__MEDIUM'
    POLISH__PL_PL__MC_SPEECH__MEDIUM = 'POLISH__PL_PL__MC_SPEECH__MEDIUM'
    POLISH__PL_PL__MLS_6892__LOW = 'POLISH__PL_PL__MLS_6892__LOW'
    PORTUGUESE__PT_BR__EDRESSON__LOW = 'PORTUGUESE__PT_BR__EDRESSON__LOW'
    PORTUGUESE__PT_BR__FABER__MEDIUM = 'PORTUGUESE__PT_BR__FABER__MEDIUM'
    PORTUGUESE__PT_PT__TUGÃO__MEDIUM = 'PORTUGUESE__PT_PT__TUGÃO__MEDIUM'
    ROMANIAN__RO_RO__MIHAI__MEDIUM = 'ROMANIAN__RO_RO__MIHAI__MEDIUM'
    RUSSIAN__RU_RU__DENIS__MEDIUM = 'RUSSIAN__RU_RU__DENIS__MEDIUM'
    RUSSIAN__RU_RU__DMITRI__MEDIUM = 'RUSSIAN__RU_RU__DMITRI__MEDIUM'
    RUSSIAN__RU_RU__IRINA__MEDIUM = 'RUSSIAN__RU_RU__IRINA__MEDIUM'
    RUSSIAN__RU_RU__RUSLAN__MEDIUM = 'RUSSIAN__RU_RU__RUSLAN__MEDIUM'
    SLOVAK__SK_SK__LILI__MEDIUM = 'SLOVAK__SK_SK__LILI__MEDIUM'
    SLOVENIAN__SL_SI__ARTUR__MEDIUM = 'SLOVENIAN__SL_SI__ARTUR__MEDIUM'
    SERBIAN__SR_RS__SERBSKI_INSTITUT__MEDIUM = 'SERBIAN__SR_RS__SERBSKI_INSTITUT__MEDIUM'
    SWEDISH__SV_SE__NST__MEDIUM = 'SWEDISH__SV_SE__NST__MEDIUM'
    SWAHILI__SW_CD__LANFRICA__MEDIUM = 'SWAHILI__SW_CD__LANFRICA__MEDIUM'
    TURKISH__TR_TR__DFKI__MEDIUM = 'TURKISH__TR_TR__DFKI__MEDIUM'
    TURKISH__TR_TR__FAHRETTIN__MEDIUM = 'TURKISH__TR_TR__FAHRETTIN__MEDIUM'
    TURKISH__TR_TR__FETTAH__MEDIUM = 'TURKISH__TR_TR__FETTAH__MEDIUM'
    UKRAINIAN__UK_UA__LADA__X_LOW = 'UKRAINIAN__UK_UA__LADA__X_LOW'
    UKRAINIAN__UK_UA__UKRAINIAN_TTS__MEDIUM = 'UKRAINIAN__UK_UA__UKRAINIAN_TTS__MEDIUM'
    VIETNAMESE__VI_VN__25HOURS_SINGLE__LOW = 'VIETNAMESE__VI_VN__25HOURS_SINGLE__LOW'
    VIETNAMESE__VI_VN__VAIS1000__MEDIUM = 'VIETNAMESE__VI_VN__VAIS1000__MEDIUM'
    VIETNAMESE__VI_VN__VIVOS__X_LOW = 'VIETNAMESE__VI_VN__VIVOS__X_LOW'
    CHINESE__ZH_CN__HUAYAN__X_LOW = 'CHINESE__ZH_CN__HUAYAN__X_LOW'
    CHINESE__ZH_CN__HUAYAN__MEDIUM = 'CHINESE__ZH_CN__HUAYAN__MEDIUM'


voices_map = {
    PiperVoicesToDownload.ARABIC__AR_JO__KAREEM__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/low/ar_JO-kareem-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/low/ar_JO-kareem-low.onnx.json?download=true.json', 'name': 'ar_JO-kareem-low'},
    PiperVoicesToDownload.ARABIC__AR_JO__KAREEM__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/medium/ar_JO-kareem-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/medium/ar_JO-kareem-medium.onnx.json?download=true.json', 'name': 'ar_JO-kareem-medium'},
    PiperVoicesToDownload.CATALAN__CA_ES__UPC_ONA__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ca/ca_ES/upc_ona/x_low/ca_ES-upc_ona-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ca/ca_ES/upc_ona/x_low/ca_ES-upc_ona-x_low.onnx.json?download=true.json', 'name': 'ca_ES-upc_ona-x_low'},
    PiperVoicesToDownload.CATALAN__CA_ES__UPC_ONA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium.onnx.json?download=true.json', 'name': 'ca_ES-upc_ona-medium'},
    PiperVoicesToDownload.CATALAN__CA_ES__UPC_PAU__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ca/ca_ES/upc_pau/x_low/ca_ES-upc_pau-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ca/ca_ES/upc_pau/x_low/ca_ES-upc_pau-x_low.onnx.json?download=true.json', 'name': 'ca_ES-upc_pau-x_low'},
    PiperVoicesToDownload.CZECH__CS_CZ__JIRKA__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/cs/cs_CZ/jirka/low/cs_CZ-jirka-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/cs/cs_CZ/jirka/low/cs_CZ-jirka-low.onnx.json?download=true.json', 'name': 'cs_CZ-jirka-low'},
    PiperVoicesToDownload.CZECH__CS_CZ__JIRKA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/cs/cs_CZ/jirka/medium/cs_CZ-jirka-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/cs/cs_CZ/jirka/medium/cs_CZ-jirka-medium.onnx.json?download=true.json', 'name': 'cs_CZ-jirka-medium'},
    PiperVoicesToDownload.WELSH__CY_GB__GWRYW_GOGLEDDOL__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/cy/cy_GB/gwryw_gogleddol/medium/cy_GB-gwryw_gogleddol-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/cy/cy_GB/gwryw_gogleddol/medium/cy_GB-gwryw_gogleddol-medium.onnx.json?download=true.json', 'name': 'cy_GB-gwryw_gogleddol-medium'},
    PiperVoicesToDownload.DANISH__DA_DK__TALESYNTESE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/da/da_DK/talesyntese/medium/da_DK-talesyntese-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/da/da_DK/talesyntese/medium/da_DK-talesyntese-medium.onnx.json?download=true.json', 'name': 'da_DK-talesyntese-medium'},
    PiperVoicesToDownload.GERMAN__DE_DE__EVA_K__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/eva_k/x_low/de_DE-eva_k-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/eva_k/x_low/de_DE-eva_k-x_low.onnx.json?download=true.json', 'name': 'de_DE-eva_k-x_low'},
    PiperVoicesToDownload.GERMAN__DE_DE__KARLSSON__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/karlsson/low/de_DE-karlsson-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/karlsson/low/de_DE-karlsson-low.onnx.json?download=true.json', 'name': 'de_DE-karlsson-low'},
    PiperVoicesToDownload.GERMAN__DE_DE__KERSTIN__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/kerstin/low/de_DE-kerstin-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/kerstin/low/de_DE-kerstin-low.onnx.json?download=true.json', 'name': 'de_DE-kerstin-low'},
    PiperVoicesToDownload.GERMAN__DE_DE__MLS__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/mls/medium/de_DE-mls-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/mls/medium/de_DE-mls-medium.onnx.json?download=true.json', 'name': 'de_DE-mls-medium'},
    PiperVoicesToDownload.GERMAN__DE_DE__PAVOQUE__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/pavoque/low/de_DE-pavoque-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/pavoque/low/de_DE-pavoque-low.onnx.json?download=true.json', 'name': 'de_DE-pavoque-low'},
    PiperVoicesToDownload.GERMAN__DE_DE__RAMONA__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/ramona/low/de_DE-ramona-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/ramona/low/de_DE-ramona-low.onnx.json?download=true.json', 'name': 'de_DE-ramona-low'},
    PiperVoicesToDownload.GERMAN__DE_DE__THORSTEN__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten/low/de_DE-thorsten-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten/low/de_DE-thorsten-low.onnx.json?download=true.json', 'name': 'de_DE-thorsten-low'},
    PiperVoicesToDownload.GERMAN__DE_DE__THORSTEN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten/medium/de_DE-thorsten-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten/medium/de_DE-thorsten-medium.onnx.json?download=true.json', 'name': 'de_DE-thorsten-medium'},
    PiperVoicesToDownload.GERMAN__DE_DE__THORSTEN__HIGH: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten/high/de_DE-thorsten-high.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten/high/de_DE-thorsten-high.onnx.json?download=true.json', 'name': 'de_DE-thorsten-high'},
    PiperVoicesToDownload.GERMAN__DE_DE__THORSTEN_EMOTIONAL__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten_emotional/medium/de_DE-thorsten_emotional-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten_emotional/medium/de_DE-thorsten_emotional-medium.onnx.json?download=true.json', 'name': 'de_DE-thorsten_emotional-medium'},
    PiperVoicesToDownload.GREEK__EL_GR__RAPUNZELINA__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/el/el_GR/rapunzelina/low/el_GR-rapunzelina-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/el/el_GR/rapunzelina/low/el_GR-rapunzelina-low.onnx.json?download=true.json', 'name': 'el_GR-rapunzelina-low'},
    PiperVoicesToDownload.ENGLISH__EN_GB__ALAN__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alan/low/en_GB-alan-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alan/low/en_GB-alan-low.onnx.json?download=true.json', 'name': 'en_GB-alan-low'},
    PiperVoicesToDownload.ENGLISH__EN_GB__ALAN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alan/medium/en_GB-alan-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alan/medium/en_GB-alan-medium.onnx.json?download=true.json', 'name': 'en_GB-alan-medium'},
    PiperVoicesToDownload.ENGLISH__EN_GB__ALBA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alba/medium/en_GB-alba-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alba/medium/en_GB-alba-medium.onnx.json?download=true.json', 'name': 'en_GB-alba-medium'},
    PiperVoicesToDownload.ENGLISH__EN_GB__ARU__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/aru/medium/en_GB-aru-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/aru/medium/en_GB-aru-medium.onnx.json?download=true.json', 'name': 'en_GB-aru-medium'},
    PiperVoicesToDownload.ENGLISH__EN_GB__CORI__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/cori/medium/en_GB-cori-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/cori/medium/en_GB-cori-medium.onnx.json?download=true.json', 'name': 'en_GB-cori-medium'},
    PiperVoicesToDownload.ENGLISH__EN_GB__CORI__HIGH: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/cori/high/en_GB-cori-high.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/cori/high/en_GB-cori-high.onnx.json?download=true.json', 'name': 'en_GB-cori-high'},
    PiperVoicesToDownload.ENGLISH__EN_GB__JENNY_DIOCO__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx.json?download=true.json', 'name': 'en_GB-jenny_dioco-medium'},
    PiperVoicesToDownload.ENGLISH__EN_GB__NORTHERN_ENGLISH_MALE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx.json?download=true.json', 'name': 'en_GB-northern_english_male-medium'},
    PiperVoicesToDownload.ENGLISH__EN_GB__SEMAINE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/semaine/medium/en_GB-semaine-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/semaine/medium/en_GB-semaine-medium.onnx.json?download=true.json', 'name': 'en_GB-semaine-medium'},
    PiperVoicesToDownload.ENGLISH__EN_GB__SOUTHERN_ENGLISH_FEMALE__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx.json?download=true.json', 'name': 'en_GB-southern_english_female-low'},
    PiperVoicesToDownload.ENGLISH__EN_GB__VCTK__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/vctk/medium/en_GB-vctk-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/vctk/medium/en_GB-vctk-medium.onnx.json?download=true.json', 'name': 'en_GB-vctk-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__AMY__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/amy/low/en_US-amy-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/amy/low/en_US-amy-low.onnx.json?download=true.json', 'name': 'en_US-amy-low'},
    PiperVoicesToDownload.ENGLISH__EN_US__AMY__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/amy/medium/en_US-amy-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/amy/medium/en_US-amy-medium.onnx.json?download=true.json', 'name': 'en_US-amy-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__ARCTIC__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/arctic/medium/en_US-arctic-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/arctic/medium/en_US-arctic-medium.onnx.json?download=true.json', 'name': 'en_US-arctic-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__BRYCE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/bryce/medium/en_US-bryce-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/bryce/medium/en_US-bryce-medium.onnx.json?download=true.json', 'name': 'en_US-bryce-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__DANNY__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/danny/low/en_US-danny-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/danny/low/en_US-danny-low.onnx.json?download=true.json', 'name': 'en_US-danny-low'},
    PiperVoicesToDownload.ENGLISH__EN_US__HFC_FEMALE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx.json?download=true.json', 'name': 'en_US-hfc_female-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__HFC_MALE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx.json?download=true.json', 'name': 'en_US-hfc_male-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__JOE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/joe/medium/en_US-joe-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/joe/medium/en_US-joe-medium.onnx.json?download=true.json', 'name': 'en_US-joe-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__JOHN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/john/medium/en_US-john-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/john/medium/en_US-john-medium.onnx.json?download=true.json', 'name': 'en_US-john-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__KATHLEEN__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/kathleen/low/en_US-kathleen-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/kathleen/low/en_US-kathleen-low.onnx.json?download=true.json', 'name': 'en_US-kathleen-low'},
    PiperVoicesToDownload.ENGLISH__EN_US__KRISTIN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/kristin/medium/en_US-kristin-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/kristin/medium/en_US-kristin-medium.onnx.json?download=true.json', 'name': 'en_US-kristin-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__KUSAL__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/kusal/medium/en_US-kusal-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/kusal/medium/en_US-kusal-medium.onnx.json?download=true.json', 'name': 'en_US-kusal-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__L2ARCTIC__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx.json?download=true.json', 'name': 'en_US-l2arctic-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__LESSAC__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/low/en_US-lessac-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/low/en_US-lessac-low.onnx.json?download=true.json', 'name': 'en_US-lessac-low'},
    PiperVoicesToDownload.ENGLISH__EN_US__LESSAC__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/medium/en_US-lessac-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/medium/en_US-lessac-medium.onnx.json?download=true.json', 'name': 'en_US-lessac-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__LESSAC__HIGH: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/high/en_US-lessac-high.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/high/en_US-lessac-high.onnx.json?download=true.json', 'name': 'en_US-lessac-high'},
    PiperVoicesToDownload.ENGLISH__EN_US__LIBRITTS__HIGH: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/libritts/high/en_US-libritts-high.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/libritts/high/en_US-libritts-high.onnx.json?download=true.json', 'name': 'en_US-libritts-high'},
    PiperVoicesToDownload.ENGLISH__EN_US__LIBRITTS_R__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx.json?download=true.json', 'name': 'en_US-libritts_r-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__LJSPEECH__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ljspeech/medium/en_US-ljspeech-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ljspeech/medium/en_US-ljspeech-medium.onnx.json?download=true.json', 'name': 'en_US-ljspeech-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__LJSPEECH__HIGH: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ljspeech/high/en_US-ljspeech-high.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ljspeech/high/en_US-ljspeech-high.onnx.json?download=true.json', 'name': 'en_US-ljspeech-high'},
    PiperVoicesToDownload.ENGLISH__EN_US__NORMAN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/norman/medium/en_US-norman-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/norman/medium/en_US-norman-medium.onnx.json?download=true.json', 'name': 'en_US-norman-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__RYAN__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ryan/low/en_US-ryan-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ryan/low/en_US-ryan-low.onnx.json?download=true.json', 'name': 'en_US-ryan-low'},
    PiperVoicesToDownload.ENGLISH__EN_US__RYAN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ryan/medium/en_US-ryan-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ryan/medium/en_US-ryan-medium.onnx.json?download=true.json', 'name': 'en_US-ryan-medium'},
    PiperVoicesToDownload.ENGLISH__EN_US__RYAN__HIGH: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ryan/high/en_US-ryan-high.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ryan/high/en_US-ryan-high.onnx.json?download=true.json', 'name': 'en_US-ryan-high'},
    PiperVoicesToDownload.SPANISH__ES_ES__CARLFM__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/carlfm/x_low/es_ES-carlfm-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/carlfm/x_low/es_ES-carlfm-x_low.onnx.json?download=true.json', 'name': 'es_ES-carlfm-x_low'},
    PiperVoicesToDownload.SPANISH__ES_ES__DAVEFX__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/davefx/medium/es_ES-davefx-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/davefx/medium/es_ES-davefx-medium.onnx.json?download=true.json', 'name': 'es_ES-davefx-medium'},
    PiperVoicesToDownload.SPANISH__ES_ES__MLS_10246__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/mls_10246/low/es_ES-mls_10246-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/mls_10246/low/es_ES-mls_10246-low.onnx.json?download=true.json', 'name': 'es_ES-mls_10246-low'},
    PiperVoicesToDownload.SPANISH__ES_ES__MLS_9972__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/mls_9972/low/es_ES-mls_9972-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/mls_9972/low/es_ES-mls_9972-low.onnx.json?download=true.json', 'name': 'es_ES-mls_9972-low'},
    PiperVoicesToDownload.SPANISH__ES_ES__SHARVARD__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/sharvard/medium/es_ES-sharvard-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/sharvard/medium/es_ES-sharvard-medium.onnx.json?download=true.json', 'name': 'es_ES-sharvard-medium'},
    PiperVoicesToDownload.SPANISH__ES_MX__ALD__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_MX/ald/medium/es_MX-ald-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_MX/ald/medium/es_MX-ald-medium.onnx.json?download=true.json', 'name': 'es_MX-ald-medium'},
    PiperVoicesToDownload.SPANISH__ES_MX__CLAUDE__HIGH: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_MX/claude/high/es_MX-claude-high.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_MX/claude/high/es_MX-claude-high.onnx.json?download=true.json', 'name': 'es_MX-claude-high'},
    PiperVoicesToDownload.FARSI__FA_IR__AMIR__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fa/fa_IR/amir/medium/fa_IR-amir-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fa/fa_IR/amir/medium/fa_IR-amir-medium.onnx.json?download=true.json', 'name': 'fa_IR-amir-medium'},
    PiperVoicesToDownload.FARSI__FA_IR__GYRO__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fa/fa_IR/gyro/medium/fa_IR-gyro-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fa/fa_IR/gyro/medium/fa_IR-gyro-medium.onnx.json?download=true.json', 'name': 'fa_IR-gyro-medium'},
    PiperVoicesToDownload.FINNISH__FI_FI__HARRI__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fi/fi_FI/harri/low/fi_FI-harri-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fi/fi_FI/harri/low/fi_FI-harri-low.onnx.json?download=true.json', 'name': 'fi_FI-harri-low'},
    PiperVoicesToDownload.FINNISH__FI_FI__HARRI__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fi/fi_FI/harri/medium/fi_FI-harri-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fi/fi_FI/harri/medium/fi_FI-harri-medium.onnx.json?download=true.json', 'name': 'fi_FI-harri-medium'},
    PiperVoicesToDownload.FRENCH__FR_FR__GILLES__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/gilles/low/fr_FR-gilles-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/gilles/low/fr_FR-gilles-low.onnx.json?download=true.json', 'name': 'fr_FR-gilles-low'},
    PiperVoicesToDownload.FRENCH__FR_FR__MLS__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/mls/medium/fr_FR-mls-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/mls/medium/fr_FR-mls-medium.onnx.json?download=true.json', 'name': 'fr_FR-mls-medium'},
    PiperVoicesToDownload.FRENCH__FR_FR__MLS_1840__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/mls_1840/low/fr_FR-mls_1840-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/mls_1840/low/fr_FR-mls_1840-low.onnx.json?download=true.json', 'name': 'fr_FR-mls_1840-low'},
    PiperVoicesToDownload.FRENCH__FR_FR__SIWIS__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/siwis/low/fr_FR-siwis-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/siwis/low/fr_FR-siwis-low.onnx.json?download=true.json', 'name': 'fr_FR-siwis-low'},
    PiperVoicesToDownload.FRENCH__FR_FR__SIWIS__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx.json?download=true.json', 'name': 'fr_FR-siwis-medium'},
    PiperVoicesToDownload.FRENCH__FR_FR__TOM__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/tom/medium/fr_FR-tom-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/tom/medium/fr_FR-tom-medium.onnx.json?download=true.json', 'name': 'fr_FR-tom-medium'},
    PiperVoicesToDownload.FRENCH__FR_FR__UPMC__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/upmc/medium/fr_FR-upmc-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/upmc/medium/fr_FR-upmc-medium.onnx.json?download=true.json', 'name': 'fr_FR-upmc-medium'},
    PiperVoicesToDownload.HUNGARIAN__HU_HU__ANNA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/hu/hu_HU/anna/medium/hu_HU-anna-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/hu/hu_HU/anna/medium/hu_HU-anna-medium.onnx.json?download=true.json', 'name': 'hu_HU-anna-medium'},
    PiperVoicesToDownload.HUNGARIAN__HU_HU__BERTA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/hu/hu_HU/berta/medium/hu_HU-berta-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/hu/hu_HU/berta/medium/hu_HU-berta-medium.onnx.json?download=true.json', 'name': 'hu_HU-berta-medium'},
    PiperVoicesToDownload.HUNGARIAN__HU_HU__IMRE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/hu/hu_HU/imre/medium/hu_HU-imre-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/hu/hu_HU/imre/medium/hu_HU-imre-medium.onnx.json?download=true.json', 'name': 'hu_HU-imre-medium'},
    PiperVoicesToDownload.ICELANDIC__IS_IS__BUI__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/is/is_IS/bui/medium/is_IS-bui-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/is/is_IS/bui/medium/is_IS-bui-medium.onnx.json?download=true.json', 'name': 'is_IS-bui-medium'},
    PiperVoicesToDownload.ICELANDIC__IS_IS__SALKA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/is/is_IS/salka/medium/is_IS-salka-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/is/is_IS/salka/medium/is_IS-salka-medium.onnx.json?download=true.json', 'name': 'is_IS-salka-medium'},
    PiperVoicesToDownload.ICELANDIC__IS_IS__STEINN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/is/is_IS/steinn/medium/is_IS-steinn-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/is/is_IS/steinn/medium/is_IS-steinn-medium.onnx.json?download=true.json', 'name': 'is_IS-steinn-medium'},
    PiperVoicesToDownload.ICELANDIC__IS_IS__UGLA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/is/is_IS/ugla/medium/is_IS-ugla-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/is/is_IS/ugla/medium/is_IS-ugla-medium.onnx.json?download=true.json', 'name': 'is_IS-ugla-medium'},
    PiperVoicesToDownload.ITALIAN__IT_IT__PAOLA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/it/it_IT/paola/medium/it_IT-paola-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/it/it_IT/paola/medium/it_IT-paola-medium.onnx.json?download=true.json', 'name': 'it_IT-paola-medium'},
    PiperVoicesToDownload.ITALIAN__IT_IT__RICCARDO__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/it/it_IT/riccardo/x_low/it_IT-riccardo-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/it/it_IT/riccardo/x_low/it_IT-riccardo-x_low.onnx.json?download=true.json', 'name': 'it_IT-riccardo-x_low'},
    PiperVoicesToDownload.GEORGIAN__KA_GE__NATIA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ka/ka_GE/natia/medium/ka_GE-natia-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ka/ka_GE/natia/medium/ka_GE-natia-medium.onnx.json?download=true.json', 'name': 'ka_GE-natia-medium'},
    PiperVoicesToDownload.KAZAKH__KK_KZ__ISEKE__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/kk/kk_KZ/iseke/x_low/kk_KZ-iseke-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/kk/kk_KZ/iseke/x_low/kk_KZ-iseke-x_low.onnx.json?download=true.json', 'name': 'kk_KZ-iseke-x_low'},
    PiperVoicesToDownload.KAZAKH__KK_KZ__ISSAI__HIGH: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/kk/kk_KZ/issai/high/kk_KZ-issai-high.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/kk/kk_KZ/issai/high/kk_KZ-issai-high.onnx.json?download=true.json', 'name': 'kk_KZ-issai-high'},
    PiperVoicesToDownload.KAZAKH__KK_KZ__RAYA__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/kk/kk_KZ/raya/x_low/kk_KZ-raya-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/kk/kk_KZ/raya/x_low/kk_KZ-raya-x_low.onnx.json?download=true.json', 'name': 'kk_KZ-raya-x_low'},
    PiperVoicesToDownload.LUXEMBOURGISH__LB_LU__MARYLUX__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/lb/lb_LU/marylux/medium/lb_LU-marylux-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/lb/lb_LU/marylux/medium/lb_LU-marylux-medium.onnx.json?download=true.json', 'name': 'lb_LU-marylux-medium'},
    PiperVoicesToDownload.NEPALI__NE_NP__GOOGLE__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ne/ne_NP/google/x_low/ne_NP-google-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ne/ne_NP/google/x_low/ne_NP-google-x_low.onnx.json?download=true.json', 'name': 'ne_NP-google-x_low'},
    PiperVoicesToDownload.NEPALI__NE_NP__GOOGLE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ne/ne_NP/google/medium/ne_NP-google-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ne/ne_NP/google/medium/ne_NP-google-medium.onnx.json?download=true.json', 'name': 'ne_NP-google-medium'},
    PiperVoicesToDownload.DUTCH__NL_BE__NATHALIE__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_BE/nathalie/x_low/nl_BE-nathalie-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_BE/nathalie/x_low/nl_BE-nathalie-x_low.onnx.json?download=true.json', 'name': 'nl_BE-nathalie-x_low'},
    PiperVoicesToDownload.DUTCH__NL_BE__NATHALIE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_BE/nathalie/medium/nl_BE-nathalie-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_BE/nathalie/medium/nl_BE-nathalie-medium.onnx.json?download=true.json', 'name': 'nl_BE-nathalie-medium'},
    PiperVoicesToDownload.DUTCH__NL_BE__RDH__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_BE/rdh/x_low/nl_BE-rdh-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_BE/rdh/x_low/nl_BE-rdh-x_low.onnx.json?download=true.json', 'name': 'nl_BE-rdh-x_low'},
    PiperVoicesToDownload.DUTCH__NL_BE__RDH__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_BE/rdh/medium/nl_BE-rdh-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_BE/rdh/medium/nl_BE-rdh-medium.onnx.json?download=true.json', 'name': 'nl_BE-rdh-medium'},
    PiperVoicesToDownload.DUTCH__NL_NL__MLS__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_NL/mls/medium/nl_NL-mls-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_NL/mls/medium/nl_NL-mls-medium.onnx.json?download=true.json', 'name': 'nl_NL-mls-medium'},
    PiperVoicesToDownload.DUTCH__NL_NL__MLS_5809__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_NL/mls_5809/low/nl_NL-mls_5809-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_NL/mls_5809/low/nl_NL-mls_5809-low.onnx.json?download=true.json', 'name': 'nl_NL-mls_5809-low'},
    PiperVoicesToDownload.DUTCH__NL_NL__MLS_7432__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_NL/mls_7432/low/nl_NL-mls_7432-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_NL/mls_7432/low/nl_NL-mls_7432-low.onnx.json?download=true.json', 'name': 'nl_NL-mls_7432-low'},
    PiperVoicesToDownload.NORWEGIAN__NO_NO__TALESYNTESE__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/no/no_NO/talesyntese/medium/no_NO-talesyntese-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/no/no_NO/talesyntese/medium/no_NO-talesyntese-medium.onnx.json?download=true.json', 'name': 'no_NO-talesyntese-medium'},
    PiperVoicesToDownload.POLISH__PL_PL__DARKMAN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/darkman/medium/pl_PL-darkman-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/darkman/medium/pl_PL-darkman-medium.onnx.json?download=true.json', 'name': 'pl_PL-darkman-medium'},
    PiperVoicesToDownload.POLISH__PL_PL__GOSIA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/gosia/medium/pl_PL-gosia-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/gosia/medium/pl_PL-gosia-medium.onnx.json?download=true.json', 'name': 'pl_PL-gosia-medium'},
    PiperVoicesToDownload.POLISH__PL_PL__MC_SPEECH__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/mc_speech/medium/pl_PL-mc_speech-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/mc_speech/medium/pl_PL-mc_speech-medium.onnx.json?download=true.json', 'name': 'pl_PL-mc_speech-medium'},
    PiperVoicesToDownload.POLISH__PL_PL__MLS_6892__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/mls_6892/low/pl_PL-mls_6892-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/mls_6892/low/pl_PL-mls_6892-low.onnx.json?download=true.json', 'name': 'pl_PL-mls_6892-low'},
    PiperVoicesToDownload.PORTUGUESE__PT_BR__EDRESSON__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pt/pt_BR/edresson/low/pt_BR-edresson-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pt/pt_BR/edresson/low/pt_BR-edresson-low.onnx.json?download=true.json', 'name': 'pt_BR-edresson-low'},
    PiperVoicesToDownload.PORTUGUESE__PT_BR__FABER__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx.json?download=true.json', 'name': 'pt_BR-faber-medium'},
    PiperVoicesToDownload.PORTUGUESE__PT_PT__TUGÃO__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pt/pt_PT/tugão/medium/pt_PT-tugão-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pt/pt_PT/tugão/medium/pt_PT-tugão-medium.onnx.json?download=true.json', 'name': 'pt_PT-tugão-medium'},
    PiperVoicesToDownload.ROMANIAN__RO_RO__MIHAI__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ro/ro_RO/mihai/medium/ro_RO-mihai-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ro/ro_RO/mihai/medium/ro_RO-mihai-medium.onnx.json?download=true.json', 'name': 'ro_RO-mihai-medium'},
    PiperVoicesToDownload.RUSSIAN__RU_RU__DENIS__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/denis/medium/ru_RU-denis-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/denis/medium/ru_RU-denis-medium.onnx.json?download=true.json', 'name': 'ru_RU-denis-medium'},
    PiperVoicesToDownload.RUSSIAN__RU_RU__DMITRI__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/dmitri/medium/ru_RU-dmitri-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/dmitri/medium/ru_RU-dmitri-medium.onnx.json?download=true.json', 'name': 'ru_RU-dmitri-medium'},
    PiperVoicesToDownload.RUSSIAN__RU_RU__IRINA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx.json?download=true.json', 'name': 'ru_RU-irina-medium'},
    PiperVoicesToDownload.RUSSIAN__RU_RU__RUSLAN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/ruslan/medium/ru_RU-ruslan-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/ruslan/medium/ru_RU-ruslan-medium.onnx.json?download=true.json', 'name': 'ru_RU-ruslan-medium'},
    PiperVoicesToDownload.SLOVAK__SK_SK__LILI__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sk/sk_SK/lili/medium/sk_SK-lili-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sk/sk_SK/lili/medium/sk_SK-lili-medium.onnx.json?download=true.json', 'name': 'sk_SK-lili-medium'},
    PiperVoicesToDownload.SLOVENIAN__SL_SI__ARTUR__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sl/sl_SI/artur/medium/sl_SI-artur-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sl/sl_SI/artur/medium/sl_SI-artur-medium.onnx.json?download=true.json', 'name': 'sl_SI-artur-medium'},
    PiperVoicesToDownload.SERBIAN__SR_RS__SERBSKI_INSTITUT__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sr/sr_RS/serbski_institut/medium/sr_RS-serbski_institut-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sr/sr_RS/serbski_institut/medium/sr_RS-serbski_institut-medium.onnx.json?download=true.json', 'name': 'sr_RS-serbski_institut-medium'},
    PiperVoicesToDownload.SWEDISH__SV_SE__NST__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx.json?download=true.json', 'name': 'sv_SE-nst-medium'},
    PiperVoicesToDownload.SWAHILI__SW_CD__LANFRICA__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sw/sw_CD/lanfrica/medium/sw_CD-lanfrica-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sw/sw_CD/lanfrica/medium/sw_CD-lanfrica-medium.onnx.json?download=true.json', 'name': 'sw_CD-lanfrica-medium'},
    PiperVoicesToDownload.TURKISH__TR_TR__DFKI__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx.json?download=true.json', 'name': 'tr_TR-dfki-medium'},
    PiperVoicesToDownload.TURKISH__TR_TR__FAHRETTIN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/tr/tr_TR/fahrettin/medium/tr_TR-fahrettin-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/tr/tr_TR/fahrettin/medium/tr_TR-fahrettin-medium.onnx.json?download=true.json', 'name': 'tr_TR-fahrettin-medium'},
    PiperVoicesToDownload.TURKISH__TR_TR__FETTAH__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/tr/tr_TR/fettah/medium/tr_TR-fettah-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/tr/tr_TR/fettah/medium/tr_TR-fettah-medium.onnx.json?download=true.json', 'name': 'tr_TR-fettah-medium'},
    PiperVoicesToDownload.UKRAINIAN__UK_UA__LADA__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/uk/uk_UA/lada/x_low/uk_UA-lada-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/uk/uk_UA/lada/x_low/uk_UA-lada-x_low.onnx.json?download=true.json', 'name': 'uk_UA-lada-x_low'},
    PiperVoicesToDownload.UKRAINIAN__UK_UA__UKRAINIAN_TTS__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/uk/uk_UA/ukrainian_tts/medium/uk_UA-ukrainian_tts-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/uk/uk_UA/ukrainian_tts/medium/uk_UA-ukrainian_tts-medium.onnx.json?download=true.json', 'name': 'uk_UA-ukrainian_tts-medium'},
    PiperVoicesToDownload.VIETNAMESE__VI_VN__25HOURS_SINGLE__LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/vi/vi_VN/25hours_single/low/vi_VN-25hours_single-low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/vi/vi_VN/25hours_single/low/vi_VN-25hours_single-low.onnx.json?download=true.json', 'name': 'vi_VN-25hours_single-low'},
    PiperVoicesToDownload.VIETNAMESE__VI_VN__VAIS1000__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/vi/vi_VN/vais1000/medium/vi_VN-vais1000-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/vi/vi_VN/vais1000/medium/vi_VN-vais1000-medium.onnx.json?download=true.json', 'name': 'vi_VN-vais1000-medium'},
    PiperVoicesToDownload.VIETNAMESE__VI_VN__VIVOS__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/vi/vi_VN/vivos/x_low/vi_VN-vivos-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/vi/vi_VN/vivos/x_low/vi_VN-vivos-x_low.onnx.json?download=true.json', 'name': 'vi_VN-vivos-x_low'},
    PiperVoicesToDownload.CHINESE__ZH_CN__HUAYAN__X_LOW: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/zh/zh_CN/huayan/x_low/zh_CN-huayan-x_low.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/zh/zh_CN/huayan/x_low/zh_CN-huayan-x_low.onnx.json?download=true.json', 'name': 'zh_CN-huayan-x_low'},
    PiperVoicesToDownload.CHINESE__ZH_CN__HUAYAN__MEDIUM: {'model': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/zh/zh_CN/huayan/medium/zh_CN-huayan-medium.onnx?download=true', 'config': 'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/zh/zh_CN/huayan/medium/zh_CN-huayan-medium.onnx.json?download=true.json', 'name': 'zh_CN-huayan-medium'},
}
